// Code generated by mockery v2.36.0. DO NOT EDIT.

package mock_repository

import (
	"im/internal/models/po"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	req "im/internal/models/request"
)

// MockLoginRecordRepository is an autogenerated mock type for the ILoginRecordRepository type
type MockLoginRecordRepository struct {
	mock.Mock
}

type MockLoginRecordRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginRecordRepository) EXPECT() *MockLoginRecordRepository_Expecter {
	return &MockLoginRecordRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: db, data
func (_m *MockLoginRecordRepository) Create(db *gorm.DB, data *po.LoginRecord) (interface{}, error) {
	ret := _m.Called(db, data)

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *po.LoginRecord) (interface{}, error)); ok {
		return rf(db, data)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, *po.LoginRecord) interface{}); ok {
		r0 = rf(db, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, *po.LoginRecord) error); ok {
		r1 = rf(db, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginRecordRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockLoginRecordRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - db *gorm.DB
//   - data *models.LoginRecord
func (_e *MockLoginRecordRepository_Expecter) Create(db interface{}, data interface{}) *MockLoginRecordRepository_Create_Call {
	return &MockLoginRecordRepository_Create_Call{Call: _e.mock.On("Create", db, data)}
}

func (_c *MockLoginRecordRepository_Create_Call) Run(run func(db *gorm.DB, data *po.LoginRecord)) *MockLoginRecordRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*po.LoginRecord))
	})
	return _c
}

func (_c *MockLoginRecordRepository_Create_Call) Return(id interface{}, err error) *MockLoginRecordRepository_Create_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *MockLoginRecordRepository_Create_Call) RunAndReturn(run func(*gorm.DB, *po.LoginRecord) (interface{}, error)) *MockLoginRecordRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: db, id
func (_m *MockLoginRecordRepository) Delete(db *gorm.DB, id string) error {
	ret := _m.Called(db, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) error); ok {
		r0 = rf(db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginRecordRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLoginRecordRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - db *gorm.DB
//   - id string
func (_e *MockLoginRecordRepository_Expecter) Delete(db interface{}, id interface{}) *MockLoginRecordRepository_Delete_Call {
	return &MockLoginRecordRepository_Delete_Call{Call: _e.mock.On("Delete", db, id)}
}

func (_c *MockLoginRecordRepository_Delete_Call) Run(run func(db *gorm.DB, id string)) *MockLoginRecordRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(string))
	})
	return _c
}

func (_c *MockLoginRecordRepository_Delete_Call) Return(err error) *MockLoginRecordRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginRecordRepository_Delete_Call) RunAndReturn(run func(*gorm.DB, string) error) *MockLoginRecordRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: db, cond
func (_m *MockLoginRecordRepository) Get(db *gorm.DB, cond *req.LoginRecordGet) (*po.LoginRecord, error) {
	ret := _m.Called(db, cond)

	var r0 *po.LoginRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *req.LoginRecordGet) (*po.LoginRecord, error)); ok {
		return rf(db, cond)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, *req.LoginRecordGet) *po.LoginRecord); ok {
		r0 = rf(db, cond)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*po.LoginRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, *req.LoginRecordGet) error); ok {
		r1 = rf(db, cond)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginRecordRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLoginRecordRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - db *gorm.DB
//   - cond *request.LoginRecordGet
func (_e *MockLoginRecordRepository_Expecter) Get(db interface{}, cond interface{}) *MockLoginRecordRepository_Get_Call {
	return &MockLoginRecordRepository_Get_Call{Call: _e.mock.On("Get", db, cond)}
}

func (_c *MockLoginRecordRepository_Get_Call) Run(run func(db *gorm.DB, cond *req.LoginRecordGet)) *MockLoginRecordRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*req.LoginRecordGet))
	})
	return _c
}

func (_c *MockLoginRecordRepository_Get_Call) Return(_a0 *po.LoginRecord, _a1 error) *MockLoginRecordRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginRecordRepository_Get_Call) RunAndReturn(run func(*gorm.DB, *req.LoginRecordGet) (*po.LoginRecord, error)) *MockLoginRecordRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: db, cond
func (_m *MockLoginRecordRepository) GetList(db *gorm.DB, cond *req.LoginRecordGetList) (*po.PageResult[*po.LoginRecord], error) {
	ret := _m.Called(db, cond)

	var r0 *po.PageResult[*po.LoginRecord]
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *req.LoginRecordGetList) (*po.PageResult[*po.LoginRecord], error)); ok {
		return rf(db, cond)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, *req.LoginRecordGetList) *po.PageResult[*po.LoginRecord]); ok {
		r0 = rf(db, cond)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*po.PageResult[*po.LoginRecord])
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, *req.LoginRecordGetList) error); ok {
		r1 = rf(db, cond)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoginRecordRepository_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockLoginRecordRepository_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - db *gorm.DB
//   - cond *request.LoginRecordGetList
func (_e *MockLoginRecordRepository_Expecter) GetList(db interface{}, cond interface{}) *MockLoginRecordRepository_GetList_Call {
	return &MockLoginRecordRepository_GetList_Call{Call: _e.mock.On("GetList", db, cond)}
}

func (_c *MockLoginRecordRepository_GetList_Call) Run(run func(db *gorm.DB, cond *req.LoginRecordGetList)) *MockLoginRecordRepository_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*req.LoginRecordGetList))
	})
	return _c
}

func (_c *MockLoginRecordRepository_GetList_Call) Return(_a0 *po.PageResult[*po.LoginRecord], _a1 error) *MockLoginRecordRepository_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoginRecordRepository_GetList_Call) RunAndReturn(run func(*gorm.DB, *req.LoginRecordGetList) (*po.PageResult[*po.LoginRecord], error)) *MockLoginRecordRepository_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: db, data
func (_m *MockLoginRecordRepository) Update(db *gorm.DB, data *po.LoginRecord) error {
	ret := _m.Called(db, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *po.LoginRecord) error); ok {
		r0 = rf(db, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoginRecordRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockLoginRecordRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - db *gorm.DB
//   - data *models.LoginRecord
func (_e *MockLoginRecordRepository_Expecter) Update(db interface{}, data interface{}) *MockLoginRecordRepository_Update_Call {
	return &MockLoginRecordRepository_Update_Call{Call: _e.mock.On("Update", db, data)}
}

func (_c *MockLoginRecordRepository_Update_Call) Run(run func(db *gorm.DB, data *po.LoginRecord)) *MockLoginRecordRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*po.LoginRecord))
	})
	return _c
}

func (_c *MockLoginRecordRepository_Update_Call) Return(err error) *MockLoginRecordRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoginRecordRepository_Update_Call) RunAndReturn(run func(*gorm.DB, *po.LoginRecord) error) *MockLoginRecordRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoginRecordRepository creates a new instance of MockLoginRecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginRecordRepository {
	mock := &MockLoginRecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
