// Code generated by mockery v2.36.0. DO NOT EDIT.

package mock_repository

import (
	models "im/internal/models"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	req "im/internal/models/request"
)

// MockGroupInvitationRepository is an autogenerated mock type for the IGroupInvitationRepository type
type MockGroupInvitationRepository struct {
	mock.Mock
}

type MockGroupInvitationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupInvitationRepository) EXPECT() *MockGroupInvitationRepository_Expecter {
	return &MockGroupInvitationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: db, data
func (_m *MockGroupInvitationRepository) Create(db *gorm.DB, data *models.GroupInvitation) (interface{}, error) {
	ret := _m.Called(db, data)

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.GroupInvitation) (interface{}, error)); ok {
		return rf(db, data)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.GroupInvitation) interface{}); ok {
		r0 = rf(db, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, *models.GroupInvitation) error); ok {
		r1 = rf(db, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupInvitationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGroupInvitationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - db *gorm.DB
//   - data *models.GroupInvitation
func (_e *MockGroupInvitationRepository_Expecter) Create(db interface{}, data interface{}) *MockGroupInvitationRepository_Create_Call {
	return &MockGroupInvitationRepository_Create_Call{Call: _e.mock.On("Create", db, data)}
}

func (_c *MockGroupInvitationRepository_Create_Call) Run(run func(db *gorm.DB, data *models.GroupInvitation)) *MockGroupInvitationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.GroupInvitation))
	})
	return _c
}

func (_c *MockGroupInvitationRepository_Create_Call) Return(id interface{}, err error) *MockGroupInvitationRepository_Create_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *MockGroupInvitationRepository_Create_Call) RunAndReturn(run func(*gorm.DB, *models.GroupInvitation) (interface{}, error)) *MockGroupInvitationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: db, id
func (_m *MockGroupInvitationRepository) Delete(db *gorm.DB, id string) error {
	ret := _m.Called(db, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, string) error); ok {
		r0 = rf(db, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupInvitationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGroupInvitationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - db *gorm.DB
//   - id string
func (_e *MockGroupInvitationRepository_Expecter) Delete(db interface{}, id interface{}) *MockGroupInvitationRepository_Delete_Call {
	return &MockGroupInvitationRepository_Delete_Call{Call: _e.mock.On("Delete", db, id)}
}

func (_c *MockGroupInvitationRepository_Delete_Call) Run(run func(db *gorm.DB, id string)) *MockGroupInvitationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(string))
	})
	return _c
}

func (_c *MockGroupInvitationRepository_Delete_Call) Return(err error) *MockGroupInvitationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupInvitationRepository_Delete_Call) RunAndReturn(run func(*gorm.DB, string) error) *MockGroupInvitationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: db, cond
func (_m *MockGroupInvitationRepository) Get(db *gorm.DB, cond *req.GroupInvitationGet) (*models.GroupInvitation, error) {
	ret := _m.Called(db, cond)

	var r0 *models.GroupInvitation
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *req.GroupInvitationGet) (*models.GroupInvitation, error)); ok {
		return rf(db, cond)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, *req.GroupInvitationGet) *models.GroupInvitation); ok {
		r0 = rf(db, cond)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.GroupInvitation)
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, *req.GroupInvitationGet) error); ok {
		r1 = rf(db, cond)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupInvitationRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGroupInvitationRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - db *gorm.DB
//   - cond *request.GroupInvitationGet
func (_e *MockGroupInvitationRepository_Expecter) Get(db interface{}, cond interface{}) *MockGroupInvitationRepository_Get_Call {
	return &MockGroupInvitationRepository_Get_Call{Call: _e.mock.On("Get", db, cond)}
}

func (_c *MockGroupInvitationRepository_Get_Call) Run(run func(db *gorm.DB, cond *req.GroupInvitationGet)) *MockGroupInvitationRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*req.GroupInvitationGet))
	})
	return _c
}

func (_c *MockGroupInvitationRepository_Get_Call) Return(_a0 *models.GroupInvitation, _a1 error) *MockGroupInvitationRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupInvitationRepository_Get_Call) RunAndReturn(run func(*gorm.DB, *req.GroupInvitationGet) (*models.GroupInvitation, error)) *MockGroupInvitationRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: db, cond
func (_m *MockGroupInvitationRepository) GetList(db *gorm.DB, cond *req.GroupInvitationGetList) (*models.PageResult[*models.GroupInvitation], error) {
	ret := _m.Called(db, cond)

	var r0 *models.PageResult[*models.GroupInvitation]
	var r1 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *req.GroupInvitationGetList) (*models.PageResult[*models.GroupInvitation], error)); ok {
		return rf(db, cond)
	}
	if rf, ok := ret.Get(0).(func(*gorm.DB, *req.GroupInvitationGetList) *models.PageResult[*models.GroupInvitation]); ok {
		r0 = rf(db, cond)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PageResult[*models.GroupInvitation])
		}
	}

	if rf, ok := ret.Get(1).(func(*gorm.DB, *req.GroupInvitationGetList) error); ok {
		r1 = rf(db, cond)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupInvitationRepository_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockGroupInvitationRepository_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - db *gorm.DB
//   - cond *request.GroupInvitationGetList
func (_e *MockGroupInvitationRepository_Expecter) GetList(db interface{}, cond interface{}) *MockGroupInvitationRepository_GetList_Call {
	return &MockGroupInvitationRepository_GetList_Call{Call: _e.mock.On("GetList", db, cond)}
}

func (_c *MockGroupInvitationRepository_GetList_Call) Run(run func(db *gorm.DB, cond *req.GroupInvitationGetList)) *MockGroupInvitationRepository_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*req.GroupInvitationGetList))
	})
	return _c
}

func (_c *MockGroupInvitationRepository_GetList_Call) Return(_a0 *models.PageResult[*models.GroupInvitation], _a1 error) *MockGroupInvitationRepository_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupInvitationRepository_GetList_Call) RunAndReturn(run func(*gorm.DB, *req.GroupInvitationGetList) (*models.PageResult[*models.GroupInvitation], error)) *MockGroupInvitationRepository_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: db, data
func (_m *MockGroupInvitationRepository) Update(db *gorm.DB, data *models.GroupInvitation) error {
	ret := _m.Called(db, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(*gorm.DB, *models.GroupInvitation) error); ok {
		r0 = rf(db, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupInvitationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGroupInvitationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - db *gorm.DB
//   - data *models.GroupInvitation
func (_e *MockGroupInvitationRepository_Expecter) Update(db interface{}, data interface{}) *MockGroupInvitationRepository_Update_Call {
	return &MockGroupInvitationRepository_Update_Call{Call: _e.mock.On("Update", db, data)}
}

func (_c *MockGroupInvitationRepository_Update_Call) Run(run func(db *gorm.DB, data *models.GroupInvitation)) *MockGroupInvitationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gorm.DB), args[1].(*models.GroupInvitation))
	})
	return _c
}

func (_c *MockGroupInvitationRepository_Update_Call) Return(err error) *MockGroupInvitationRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGroupInvitationRepository_Update_Call) RunAndReturn(run func(*gorm.DB, *models.GroupInvitation) error) *MockGroupInvitationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupInvitationRepository creates a new instance of MockGroupInvitationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupInvitationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupInvitationRepository {
	mock := &MockGroupInvitationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
