config:
  log_config:
    name: "im"
    env: "local"
    level: "debug"
  mysql_config:
    master: "localhost:3306"
    slave: "localhost:3306"
    username: "root"
    password: "123456"
    database: "demo"
    max_idle: 3
    max_open: 10
    conn_max_life_min: 15
    log_mode: true
  gin_config:
    port: ":9000"
    debug_mode: true
    swagger_mode: true
  redis_config:
    address: "localhost:6379"
    Password: ""
    max_idle: 10
    max_active: 1000
    idle_timeout: 30
    connect_timeout: 0
    read_timeout: 10
    write_timeout: 3
  mongo_config:
    host: "localhost:27017"
    user: "root"
    passwd: "123456"
    db: "demo"
    max_idle_time: 5
    max_open_conn: 50
  cache_config:
    cache_size: 2097152
  rate_config:
    rate: 200
    burst: 200
    store_size: 65536
    use_memory_store: false

    