// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/blocked-friend": {
            "get": {
                "tags": [
                    "friend"
                ],
                "summary": "獲取指定用戶ID的已封鎖好友列表",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.FriendDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "friend"
                ],
                "summary": "指定用戶ID封鎖或取消封鎖指定好友ID",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.FriendDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            }
        },
        "/example": {
            "get": {
                "tags": [
                    "example"
                ],
                "summary": "GetList",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.ExampleGetList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-resp_ExampleGetList"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "example"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.ExampleUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "example"
                ],
                "summary": "Create",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.ExampleCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "example"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.ExampleDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            }
        },
        "/example/:id": {
            "get": {
                "tags": [
                    "example"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.ExampleGet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-resp_ExampleGet"
                        }
                    }
                }
            }
        },
        "/friend": {
            "get": {
                "tags": [
                    "friend"
                ],
                "summary": "獲取用戶的好友列表",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.FriendGetList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-resp_FriendGetList"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "friend"
                ],
                "summary": "更新與指定用戶的好友關係（接受/拒絕/阻止）",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.FriendUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "friend"
                ],
                "summary": "刪除與指定用戶的好友關係",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.FriendDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            }
        },
        "/friend-requests": {
            "get": {
                "tags": [
                    "FriendRequests"
                ],
                "summary": "好友請求列表",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.FriendRequestsGetList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-resp_FriendRequestsGetList"
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "FriendRequests"
                ],
                "summary": "接受或拒絕來自id的好友請求",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.FriendRequestsUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    },
                    "400": {
                        "description": "无效的ID",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    },
                    "500": {
                        "description": "未知错误",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "FriendRequests"
                ],
                "summary": "向指定用戶ID發送好友請求",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.FriendRequestsCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    },
                    "400": {
                        "description": "无效的用户",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    },
                    "409": {
                        "description": "Friend request already exists between these users.",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    },
                    "500": {
                        "description": "未知错误",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            }
        },
        "/loginRecord": {
            "get": {
                "tags": [
                    "loginRecord"
                ],
                "summary": "取得登入記錄",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.LoginRecordGetList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-resp_LoginRecordGetList"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "tags": [
                    "public"
                ],
                "summary": "Metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/mutual-friend": {
            "get": {
                "tags": [
                    "friend"
                ],
                "summary": "獲取指定用戶ID與另一指定用戶ID的共同好友列表",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.FriendDelete"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "tags": [
                    "public"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users": {
            "put": {
                "tags": [
                    "users"
                ],
                "summary": "用戶訊息修改",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.UsersUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            }
        },
        "/users/:id": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "取得用戶訊息",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.UsersGet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-resp_UsersGet"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "用戶登錄並返回授權令牌",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.UsersLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-resp_UsersLogin"
                        }
                    }
                }
            }
        },
        "/users/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "users"
                ],
                "summary": "用戶登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "tags": [
                    "users"
                ],
                "summary": "用戶註冊",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.UsersCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-string"
                        }
                    }
                }
            }
        },
        "/users/search": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "用戶清單",
                "parameters": [
                    {
                        "description": "param",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.UsersGetList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/resp.APIResponse-resp_UsersGetList"
                        }
                    }
                }
            }
        },
        "/users/{id}/online-status": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "獲取指定用戶ID的在線狀態",
                "responses": {}
            },
            "put": {
                "tags": [
                    "users"
                ],
                "summary": "更新指定用戶ID的在線狀態",
                "responses": {}
            }
        }
    },
    "definitions": {
        "consts.FriendReqStatus": {
            "type": "string",
            "enum": [
                "pending"
            ],
            "x-enum-varnames": [
                "FriendReqStatusPending"
            ]
        },
        "req.ExampleCreate": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "創建範例描述",
                    "type": "string",
                    "example": "一個武林高手"
                },
                "name": {
                    "description": "創建範例名",
                    "type": "string",
                    "example": "小明"
                }
            }
        },
        "req.ExampleDelete": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "刪除範例ID",
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "req.ExampleGet": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "範例描述",
                    "type": "string",
                    "example": "取得描述"
                },
                "name": {
                    "description": "範例名",
                    "type": "string",
                    "example": "名字"
                }
            }
        },
        "req.ExampleGetList": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "範例ID列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "1",
                        "2",
                        "3",
                        "4",
                        "5",
                        "6"
                    ]
                },
                "index": {
                    "description": "頁碼",
                    "type": "integer"
                },
                "name": {
                    "description": "範例名",
                    "type": "string",
                    "example": "名字"
                },
                "order": {
                    "description": "排序",
                    "type": "string",
                    "example": "id asc"
                },
                "size": {
                    "description": "筆數",
                    "type": "integer"
                }
            }
        },
        "req.ExampleUpdate": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "description": {
                    "description": "修改範例描述",
                    "type": "string",
                    "example": "繼承小明武功但沒天分的孩子"
                },
                "id": {
                    "description": "修改範例ID",
                    "type": "string",
                    "example": "1"
                },
                "name": {
                    "description": "修改範例名",
                    "type": "string",
                    "example": "小明的孩子"
                }
            }
        },
        "req.FriendDelete": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "req.FriendGetList": {
            "type": "object",
            "properties": {
                "index": {
                    "description": "頁碼",
                    "type": "integer"
                },
                "order": {
                    "description": "排序",
                    "type": "string",
                    "example": "id asc"
                },
                "size": {
                    "description": "筆數",
                    "type": "integer"
                }
            }
        },
        "req.FriendRequestsCreate": {
            "type": "object",
            "required": [
                "user_name"
            ],
            "properties": {
                "user_name": {
                    "description": "對象用戶username",
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "req.FriendRequestsGetList": {
            "type": "object",
            "properties": {
                "index": {
                    "description": "頁碼",
                    "type": "integer"
                },
                "is_sender": {
                    "description": "true: 請求列表 false: 被請求列表",
                    "type": "boolean",
                    "example": false
                },
                "order": {
                    "description": "排序",
                    "type": "string",
                    "example": "id asc"
                },
                "size": {
                    "description": "筆數",
                    "type": "integer"
                }
            }
        },
        "req.FriendRequestsUpdate": {
            "type": "object",
            "required": [
                "request_status"
            ],
            "properties": {
                "id": {
                    "description": "請求單ID",
                    "type": "string"
                },
                "request_status": {
                    "type": "string",
                    "enum": [
                        "accepted",
                        "rejected"
                    ]
                }
            }
        },
        "req.FriendUpdate": {
            "type": "object"
        },
        "req.LoginRecordGetList": {
            "type": "object",
            "properties": {
                "index": {
                    "description": "頁碼",
                    "type": "integer"
                },
                "order": {
                    "description": "排序",
                    "type": "string",
                    "example": "id asc"
                },
                "size": {
                    "description": "筆數",
                    "type": "integer"
                }
            }
        },
        "req.UsersCreate": {
            "type": "object",
            "required": [
                "email",
                "password",
                "phone_number",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "phone_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "req.UsersGet": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "req.UsersGetList": {
            "type": "object",
            "properties": {
                "index": {
                    "description": "頁碼",
                    "type": "integer"
                },
                "order": {
                    "description": "排序",
                    "type": "string",
                    "example": "id asc"
                },
                "size": {
                    "description": "筆數",
                    "type": "integer"
                }
            }
        },
        "req.UsersLogin": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密碼",
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "description": "使用者名稱",
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "req.UsersUpdate": {
            "type": "object",
            "required": [
                "email",
                "id",
                "phone_number",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "resp.APIResponse-resp_ExampleGet": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "string"
                },
                "data": {
                    "description": "資料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/resp.ExampleGet"
                        }
                    ]
                },
                "msg": {
                    "description": "訊息",
                    "type": "string"
                }
            }
        },
        "resp.APIResponse-resp_ExampleGetList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "string"
                },
                "data": {
                    "description": "資料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/resp.ExampleGetList"
                        }
                    ]
                },
                "msg": {
                    "description": "訊息",
                    "type": "string"
                }
            }
        },
        "resp.APIResponse-resp_FriendGetList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "string"
                },
                "data": {
                    "description": "資料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/resp.FriendGetList"
                        }
                    ]
                },
                "msg": {
                    "description": "訊息",
                    "type": "string"
                }
            }
        },
        "resp.APIResponse-resp_FriendRequestsGetList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "string"
                },
                "data": {
                    "description": "資料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/resp.FriendRequestsGetList"
                        }
                    ]
                },
                "msg": {
                    "description": "訊息",
                    "type": "string"
                }
            }
        },
        "resp.APIResponse-resp_LoginRecordGetList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "string"
                },
                "data": {
                    "description": "資料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/resp.LoginRecordGetList"
                        }
                    ]
                },
                "msg": {
                    "description": "訊息",
                    "type": "string"
                }
            }
        },
        "resp.APIResponse-resp_UsersGet": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "string"
                },
                "data": {
                    "description": "資料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/resp.UsersGet"
                        }
                    ]
                },
                "msg": {
                    "description": "訊息",
                    "type": "string"
                }
            }
        },
        "resp.APIResponse-resp_UsersGetList": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "string"
                },
                "data": {
                    "description": "資料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/resp.UsersGetList"
                        }
                    ]
                },
                "msg": {
                    "description": "訊息",
                    "type": "string"
                }
            }
        },
        "resp.APIResponse-resp_UsersLogin": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "string"
                },
                "data": {
                    "description": "資料",
                    "allOf": [
                        {
                            "$ref": "#/definitions/resp.UsersLogin"
                        }
                    ]
                },
                "msg": {
                    "description": "訊息",
                    "type": "string"
                }
            }
        },
        "resp.APIResponse-string": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "string"
                },
                "data": {
                    "description": "資料",
                    "type": "string"
                },
                "msg": {
                    "description": "訊息",
                    "type": "string"
                }
            }
        },
        "resp.ExampleGet": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "id": {
                    "description": "數據ID",
                    "type": "string"
                },
                "name": {
                    "description": "範例名",
                    "type": "string"
                }
            }
        },
        "resp.ExampleGetList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resp.ExampleGet"
                    }
                },
                "page": {
                    "$ref": "#/definitions/resp.PageResponse"
                }
            }
        },
        "resp.FriendGet": {
            "type": "object"
        },
        "resp.FriendGetList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resp.FriendGet"
                    }
                },
                "page": {
                    "$ref": "#/definitions/resp.PageResponse"
                }
            }
        },
        "resp.FriendRequestsGet": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "receiverID": {
                    "type": "string"
                },
                "receiverName": {
                    "type": "string"
                },
                "requestStatus": {
                    "$ref": "#/definitions/consts.FriendReqStatus"
                },
                "senderID": {
                    "type": "string"
                },
                "senderName": {
                    "type": "string"
                }
            }
        },
        "resp.FriendRequestsGetList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resp.FriendRequestsGet"
                    }
                },
                "page": {
                    "$ref": "#/definitions/resp.PageResponse"
                }
            }
        },
        "resp.LoginRecordGet": {
            "type": "object"
        },
        "resp.LoginRecordGetList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resp.LoginRecordGet"
                    }
                },
                "page": {
                    "$ref": "#/definitions/resp.PageResponse"
                }
            }
        },
        "resp.PageResponse": {
            "type": "object",
            "properties": {
                "index": {
                    "description": "頁碼",
                    "type": "integer"
                },
                "pages": {
                    "description": "總頁數",
                    "type": "integer"
                },
                "size": {
                    "description": "筆數",
                    "type": "integer"
                },
                "total": {
                    "description": "總筆數",
                    "type": "integer"
                }
            }
        },
        "resp.UsersGet": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "電子郵件地址",
                    "type": "string"
                },
                "id": {
                    "description": "uid",
                    "type": "string"
                },
                "nickname": {
                    "description": "用戶暱稱",
                    "type": "string"
                },
                "password": {
                    "description": "密碼",
                    "type": "string"
                },
                "phone_number": {
                    "description": "手機號碼",
                    "type": "string"
                },
                "username": {
                    "description": "用戶名稱",
                    "type": "string"
                }
            }
        },
        "resp.UsersGetList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/resp.UsersGet"
                    }
                },
                "page": {
                    "$ref": "#/definitions/resp.PageResponse"
                }
            }
        },
        "resp.UsersLogin": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "登入Token",
                    "type": "string"
                },
                "username": {
                    "description": "用戶名稱",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "token",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9000",
	BasePath:         "/im",
	Schemes:          []string{"http"},
	Title:            "Im",
	Description:      "This is a project im.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
