basePath: /im
definitions:
  req.ExampleCreate:
    properties:
      description:
        description: 創建範例描述
        example: 一個武林高手
        type: string
      name:
        description: 創建範例名
        example: 小明
        type: string
    type: object
  req.ExampleDelete:
    properties:
      id:
        description: 刪除範例ID
        example: "1"
        type: string
    type: object
  req.ExampleGet:
    properties:
      description:
        description: 範例描述
        example: 取得描述
        type: string
      name:
        description: 範例名
        example: 名字
        type: string
    type: object
  req.ExampleGetList:
    properties:
      id:
        description: 範例ID列表
        example:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        items:
          type: string
        type: array
      index:
        description: 頁碼
        type: integer
      name:
        description: 範例名
        example: 名字
        type: string
      order:
        description: 排序
        example: id asc
        type: string
      size:
        description: 筆數
        type: integer
    required:
    - id
    type: object
  req.ExampleUpdate:
    properties:
      description:
        description: 修改範例描述
        example: 繼承小明武功但沒天分的孩子
        type: string
      id:
        description: 修改範例ID
        example: "1"
        type: string
      name:
        description: 修改範例名
        example: 小明的孩子
        type: string
    required:
    - id
    type: object
  req.LoginRecordCreate:
    type: object
  req.LoginRecordGetList:
    properties:
      index:
        description: 頁碼
        type: integer
      order:
        description: 排序
        example: id asc
        type: string
      size:
        description: 筆數
        type: integer
    type: object
  req.UsersCreate:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        minLength: 6
        type: string
      phone_number:
        type: string
      username:
        minLength: 6
        type: string
    required:
    - email
    - password
    - phone_number
    - username
    type: object
  req.UsersGet:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        minLength: 6
        type: string
      phone_number:
        type: string
      username:
        minLength: 6
        type: string
    required:
    - email
    - password
    - phone_number
    - username
    type: object
  req.UsersGetList:
    properties:
      index:
        description: 頁碼
        type: integer
      order:
        description: 排序
        example: id asc
        type: string
      size:
        description: 筆數
        type: integer
    type: object
  req.UsersLogin:
    properties:
      password:
        description: 密碼
        minLength: 6
        type: string
      username:
        description: 使用者名稱
        minLength: 6
        type: string
    required:
    - password
    - username
    type: object
  req.UsersUpdate:
    type: object
  resp.APIResponse-resp_ExampleGet:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.ExampleGet'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_ExampleGetList:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.ExampleGetList'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_LoginRecordGetList:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.LoginRecordGetList'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_UsersGet:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.UsersGet'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_UsersGetList:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.UsersGetList'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_UsersLogin:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.UsersLogin'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-string:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        description: 資料
        type: string
      msg:
        description: 訊息
        type: string
    type: object
  resp.ExampleGet:
    properties:
      description:
        description: 描述
        type: string
      id:
        description: 數據ID
        type: string
      name:
        description: 範例名
        type: string
    type: object
  resp.ExampleGetList:
    properties:
      data:
        items:
          $ref: '#/definitions/resp.ExampleGet'
        type: array
      page:
        $ref: '#/definitions/resp.PageResponse'
    type: object
  resp.LoginRecordGet:
    type: object
  resp.LoginRecordGetList:
    properties:
      data:
        items:
          $ref: '#/definitions/resp.LoginRecordGet'
        type: array
      page:
        $ref: '#/definitions/resp.PageResponse'
    type: object
  resp.PageResponse:
    properties:
      index:
        description: 頁碼
        type: integer
      pages:
        description: 總頁數
        type: integer
      size:
        description: 筆數
        type: integer
      total:
        description: 總筆數
        type: integer
    type: object
  resp.UsersGet:
    properties:
      email:
        description: 電子郵件地址
        type: string
      nickname:
        description: 用戶暱稱
        type: string
      password:
        description: 密碼
        type: string
      phone_number:
        description: 手機號碼
        type: string
      username:
        description: 用戶名稱
        type: string
    type: object
  resp.UsersGetList:
    properties:
      data:
        items:
          $ref: '#/definitions/resp.UsersGet'
        type: array
      page:
        $ref: '#/definitions/resp.PageResponse'
    type: object
  resp.UsersLogin:
    properties:
      token:
        description: 登入Token
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:9000
info:
  contact:
    name: API Support
  description: This is a project im.
  termsOfService: http://swagger.io/terms/
  title: Im
  version: "1.0"
paths:
  /example:
    delete:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleDelete'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: Delete
      tags:
      - example
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleGetList'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_ExampleGetList'
      summary: GetList
      tags:
      - example
    post:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleCreate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: Create
      tags:
      - example
    put:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleUpdate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: Update
      tags:
      - example
  /example/:id:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleGet'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_ExampleGet'
      summary: Get
      tags:
      - example
  /loginRecord:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.LoginRecordGetList'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_LoginRecordGetList'
      summary: GetList
      tags:
      - loginRecord
    post:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.LoginRecordCreate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: Create
      tags:
      - loginRecord
  /metrics:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Metrics
      tags:
      - public
  /ping:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
      tags:
      - public
  /users:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersGetList'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_UsersGetList'
      summary: 用戶清單
      tags:
      - users
    put:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersUpdate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 用戶訊息修改
      tags:
      - users
  /users/:id:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersGet'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_UsersGet'
      summary: 取得用戶訊息
      tags:
      - users
  /users/{id}/online-status:
    get:
      responses: {}
      summary: 獲取指定用戶ID的在線狀態
      tags:
      - users
    post:
      responses: {}
      summary: 更新指定用戶ID的在線狀態
      tags:
      - users
  /users/login:
    post:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersLogin'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_UsersLogin'
      summary: 用戶登錄並返回授權令牌
      tags:
      - users
  /users/logout:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      security:
      - ApiKeyAuth: []
      summary: 用戶登出
      tags:
      - users
  /users/register:
    post:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersCreate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 用戶註冊
      tags:
      - users
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
