basePath: /im
definitions:
  consts.FriendReqStatus:
    enum:
    - pending
    type: string
    x-enum-varnames:
    - FriendReqStatusPending
  req.ExampleCreate:
    properties:
      description:
        description: 創建範例描述
        example: 一個武林高手
        type: string
      name:
        description: 創建範例名
        example: 小明
        type: string
    type: object
  req.ExampleDelete:
    properties:
      id:
        description: 刪除範例ID
        example: "1"
        type: string
    type: object
  req.ExampleGet:
    properties:
      description:
        description: 範例描述
        example: 取得描述
        type: string
      name:
        description: 範例名
        example: 名字
        type: string
    type: object
  req.ExampleGetList:
    properties:
      id:
        description: 範例ID列表
        example:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        items:
          type: string
        type: array
      index:
        description: 頁碼
        type: integer
      name:
        description: 範例名
        example: 名字
        type: string
      order:
        description: 排序
        example: id asc
        type: string
      size:
        description: 筆數
        type: integer
    required:
    - id
    type: object
  req.ExampleUpdate:
    properties:
      description:
        description: 修改範例描述
        example: 繼承小明武功但沒天分的孩子
        type: string
      id:
        description: 修改範例ID
        example: "1"
        type: string
      name:
        description: 修改範例名
        example: 小明的孩子
        type: string
    required:
    - id
    type: object
  req.FriendDelete:
    properties:
      id:
        type: string
    type: object
  req.FriendGetList:
    properties:
      index:
        description: 頁碼
        type: integer
      order:
        description: 排序
        example: id asc
        type: string
      size:
        description: 筆數
        type: integer
    type: object
  req.FriendRequestsCreate:
    properties:
      user_name:
        description: 對象用戶username
        example: user
        type: string
    required:
    - user_name
    type: object
  req.FriendRequestsGetList:
    properties:
      index:
        description: 頁碼
        type: integer
      is_sender:
        description: 'true: 請求列表 false: 被請求列表'
        example: false
        type: boolean
      order:
        description: 排序
        example: id asc
        type: string
      size:
        description: 筆數
        type: integer
    type: object
  req.FriendRequestsUpdate:
    properties:
      id:
        description: 請求單ID
        type: string
      request_status:
        enum:
        - accepted
        - rejected
        type: string
    required:
    - request_status
    type: object
  req.FriendUpdate:
    type: object
  req.LoginRecordGetList:
    properties:
      index:
        description: 頁碼
        type: integer
      order:
        description: 排序
        example: id asc
        type: string
      size:
        description: 筆數
        type: integer
    type: object
  req.UsersCreate:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        minLength: 6
        type: string
      phone_number:
        type: string
      username:
        minLength: 6
        type: string
    required:
    - email
    - password
    - phone_number
    - username
    type: object
  req.UsersGet:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
      phone_number:
        type: string
      username:
        type: string
    type: object
  req.UsersGetList:
    properties:
      index:
        description: 頁碼
        type: integer
      order:
        description: 排序
        example: id asc
        type: string
      size:
        description: 筆數
        type: integer
    type: object
  req.UsersLogin:
    properties:
      password:
        description: 密碼
        minLength: 6
        type: string
      username:
        description: 使用者名稱
        minLength: 6
        type: string
    required:
    - password
    - username
    type: object
  req.UsersUpdate:
    properties:
      email:
        type: string
      id:
        type: string
      nickname:
        type: string
      phone_number:
        type: string
      username:
        minLength: 6
        type: string
    required:
    - email
    - id
    - phone_number
    - username
    type: object
  resp.APIResponse-resp_ExampleGet:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.ExampleGet'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_ExampleGetList:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.ExampleGetList'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_FriendGetList:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.FriendGetList'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_FriendRequestsGetList:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.FriendRequestsGetList'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_LoginRecordGetList:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.LoginRecordGetList'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_UsersGet:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.UsersGet'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_UsersGetList:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.UsersGetList'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-resp_UsersLogin:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        allOf:
        - $ref: '#/definitions/resp.UsersLogin'
        description: 資料
      msg:
        description: 訊息
        type: string
    type: object
  resp.APIResponse-string:
    properties:
      code:
        description: 回傳代碼
        type: string
      data:
        description: 資料
        type: string
      msg:
        description: 訊息
        type: string
    type: object
  resp.ExampleGet:
    properties:
      description:
        description: 描述
        type: string
      id:
        description: 數據ID
        type: string
      name:
        description: 範例名
        type: string
    type: object
  resp.ExampleGetList:
    properties:
      data:
        items:
          $ref: '#/definitions/resp.ExampleGet'
        type: array
      page:
        $ref: '#/definitions/resp.PageResponse'
    type: object
  resp.FriendGet:
    type: object
  resp.FriendGetList:
    properties:
      data:
        items:
          $ref: '#/definitions/resp.FriendGet'
        type: array
      page:
        $ref: '#/definitions/resp.PageResponse'
    type: object
  resp.FriendRequestsGet:
    properties:
      createdAt:
        type: string
      id:
        type: string
      receiverID:
        type: string
      receiverName:
        type: string
      requestStatus:
        $ref: '#/definitions/consts.FriendReqStatus'
      senderID:
        type: string
      senderName:
        type: string
    type: object
  resp.FriendRequestsGetList:
    properties:
      data:
        items:
          $ref: '#/definitions/resp.FriendRequestsGet'
        type: array
      page:
        $ref: '#/definitions/resp.PageResponse'
    type: object
  resp.LoginRecordGet:
    type: object
  resp.LoginRecordGetList:
    properties:
      data:
        items:
          $ref: '#/definitions/resp.LoginRecordGet'
        type: array
      page:
        $ref: '#/definitions/resp.PageResponse'
    type: object
  resp.PageResponse:
    properties:
      index:
        description: 頁碼
        type: integer
      pages:
        description: 總頁數
        type: integer
      size:
        description: 筆數
        type: integer
      total:
        description: 總筆數
        type: integer
    type: object
  resp.UsersGet:
    properties:
      email:
        description: 電子郵件地址
        type: string
      id:
        description: uid
        type: string
      nickname:
        description: 用戶暱稱
        type: string
      password:
        description: 密碼
        type: string
      phone_number:
        description: 手機號碼
        type: string
      username:
        description: 用戶名稱
        type: string
    type: object
  resp.UsersGetList:
    properties:
      data:
        items:
          $ref: '#/definitions/resp.UsersGet'
        type: array
      page:
        $ref: '#/definitions/resp.PageResponse'
    type: object
  resp.UsersLogin:
    properties:
      token:
        description: 登入Token
        type: string
      username:
        description: 用戶名稱
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:9000
info:
  contact:
    name: API Support
  description: This is a project im.
  termsOfService: http://swagger.io/terms/
  title: Im
  version: "1.0"
paths:
  /blocked-friend:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.FriendDelete'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 獲取指定用戶ID的已封鎖好友列表
      tags:
      - friend
    put:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.FriendDelete'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 指定用戶ID封鎖或取消封鎖指定好友ID
      tags:
      - friend
  /example:
    delete:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleDelete'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: Delete
      tags:
      - example
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleGetList'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_ExampleGetList'
      summary: GetList
      tags:
      - example
    post:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleCreate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: Create
      tags:
      - example
    put:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleUpdate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: Update
      tags:
      - example
  /example/:id:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.ExampleGet'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_ExampleGet'
      summary: Get
      tags:
      - example
  /friend:
    delete:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.FriendDelete'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 刪除與指定用戶的好友關係
      tags:
      - friend
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.FriendGetList'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_FriendGetList'
      summary: 獲取用戶的好友列表
      tags:
      - friend
    put:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.FriendUpdate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 更新與指定用戶的好友關係（接受/拒絕/阻止）
      tags:
      - friend
  /friend-requests:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.FriendRequestsGetList'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_FriendRequestsGetList'
      summary: 好友請求列表
      tags:
      - FriendRequests
    post:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.FriendRequestsCreate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
        "400":
          description: 无效的用户
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
        "409":
          description: Friend request already exists between these users.
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
        "500":
          description: 未知错误
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 向指定用戶ID發送好友請求
      tags:
      - FriendRequests
    put:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.FriendRequestsUpdate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
        "400":
          description: 无效的ID
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
        "500":
          description: 未知错误
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 接受或拒絕來自id的好友請求
      tags:
      - FriendRequests
  /loginRecord:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.LoginRecordGetList'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_LoginRecordGetList'
      summary: 取得登入記錄
      tags:
      - loginRecord
  /metrics:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Metrics
      tags:
      - public
  /mutual-friend:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.FriendDelete'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 獲取指定用戶ID與另一指定用戶ID的共同好友列表
      tags:
      - friend
  /ping:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
      tags:
      - public
  /users:
    put:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersUpdate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 用戶訊息修改
      tags:
      - users
  /users/:id:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersGet'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_UsersGet'
      summary: 取得用戶訊息
      tags:
      - users
  /users/{id}/online-status:
    get:
      responses: {}
      summary: 獲取指定用戶ID的在線狀態
      tags:
      - users
    put:
      responses: {}
      summary: 更新指定用戶ID的在線狀態
      tags:
      - users
  /users/login:
    post:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersLogin'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_UsersLogin'
      summary: 用戶登錄並返回授權令牌
      tags:
      - users
  /users/logout:
    post:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      security:
      - ApiKeyAuth: []
      summary: 用戶登出
      tags:
      - users
  /users/register:
    post:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersCreate'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-string'
      summary: 用戶註冊
      tags:
      - users
  /users/search:
    get:
      parameters:
      - description: param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/req.UsersGetList'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/resp.APIResponse-resp_UsersGetList'
      summary: 用戶清單
      tags:
      - users
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
